name: Nilansh's Blog
caption: Nilansh Arora
author: Nilansh Arora
baseurl: ""
description: Welcome to the Area of Nilansh
github: http://www.github.com/nilanshz
twitter: https://twitter.com/nilansh29
##facebook: http://www.facebook.com
##linkedin: http://www.linkedin.com
email: nilansh2929 [at] gmail [dot] com
location: Gurgaon
disqus: Nilansh
##SEO
social:
  name: Nilansh
  links:
    - https://twitter.com/nilansh29
    - https://github.com/nilanshz
webmaster_verifications:
  google: oa8y9MR5B22kp07Kg_h0C5ZHqkosnQ6zeNf8x7CGP_w
  bing: CDC9B5FE4D8275A97E431F68295D6016

url: https://nilanshz.github.io


gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

##Make sure to edit the above fields, especially for disqus.
permalink: /:categories/:title.html

##highlighter: rouge ##pygments --> No Longer In Use
markdown: kramdown ##redcarpet -->No Longer in Use
##redcarpet: --> Not required
##  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
