### GENERAL SETTINGS ###

# Site settings
title: NILANSH ARORA
description: "Nilansh's Personal Site."
analytics: UA-91950225-1 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://nilansh.com"
author: Nilansh Arora
disqus_shortname: nilansh
twitter_username: nilansh29

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/nilanshz
  - title: facebook
    url: https://fb.com/nilansh.arora
  - title: twitter
    url: https://twitter.com/nilansh29
  - title: instagram
    url: https://instagram.com/niilansh_29
  - title: linkedin
    url: https://www.linkedin.com/in/nilansh-arora-791086126
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - J.K Niwas,
    - Main Bazar,
    - Moga, Punjab.
email: nilansh2929@gmail.com
tel: +91-81461-50490

# SEARCH ENGINE KNOW HTTPS
url: https://nilansh.com
enforce_ssl: nilansh.com

# JEKYLL SITEMAP
gems:
  - jekyll-sitemap

### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Short text. Shown in footer on every page and also separately on Home and Contact page.
about_author: "<del>Technocrat & altruistic </del>Working as a Full Stack Developer in Zomato , Gurgaon . Share interests including Photography, Fitness, Food and Music . Love to Party and Travel. </del>"
about_author_short: "<del> Technocrat & altruistic </del> Working as a Full Stack Developer in Zomato , Gurgaon .."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Be the first to give a testimonial!"
    author: "~"
    position: "~"
